# <span style="color:darkblue"> Lecture 12: Application 2 - Random Assignment </span>

<font size = "5">

# <span style="color:darkblue"> I. Import Libraries and Data </span>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
carfeatures = pd.read_csv("data_raw/features.csv")

# <span style="color:darkblue"> I. Random Assignment </span>

<font size = "5">

Random assignment is crucial for scientific progress ...

- The basis for medical trials
- Also used in engineering, the natural sciences and <br>
  social sciences (economics, political science, etc.)

In [3]:
# "list_status" is a list with "treatment/control" arms
# "prop_status" is the proportion in the treatment and control arms
# "size_dataset" is how many rows are contained

list_status  = ["Treatment","Control"]
prop_status  = [0.4,0.6]
size_dataset = len(carfeatures)

<font size = "5">
Random assignment

In [4]:
# The "np.random.choice" will create a vector with the status
# We will save this to a column in "carfeatures"
# Note: (i) We can always split the arguments of a function in multiple lines
#           to make it easier to read

carfeatures["status"] = np.random.choice(list_status,
                                         size = size_dataset,
                                         p = prop_status)

display(carfeatures)

,mpg,cylinders,displacement,horsepower,weight,acceleration,vehicle_id,status
0,18.0,8,307,130,3504,12.0,C-1689780,Treatment
1,15.0,8,350,165,3693,11.5,B-1689791,Control
2,18.0,8,318,150,3436,11.0,P-1689802,Control
3,16.0,8,304,150,3433,12.0,A-1689813,Treatment
4,17.0,8,302,140,3449,10.5,F-1689824,Treatment
...,...,...,...,...,...,...,...,...
393,27.0,4,140,86,2790,15.6,F-1694103,Treatment
394,44.0,4,97,52,2130,24.6,V-1694114,Control
395,32.0,4,135,84,2295,11.6,D-1694125,Control
396,28.0,4,120,79,2625,18.6,F-1694136,Control
397,31.0,4,119,82,2720,19.4,C-1694147,Control

<font size = "5">

Compute frequencies by status

In [5]:
# The command "pd.crosstab" computes frequencies
# If we add the option "normalize" it will compute proportions
# Note: The default assignment is done randomly without replacement
#       which means that the proportions are approximately the same   
#       (but not equal) to "prop_status"

frequency_table   = pd.crosstab(index = carfeatures["status"], columns = "Frequency")
proportions_table = pd.crosstab(index = carfeatures["status"],
                                columns = "Frequency",
                                normalize = True)

display(frequency_table)
display(proportions_table)

col_0      Frequency
status
Control          233
Treatment        165

col_0      Frequency
status
Control     0.585427
Treatment   0.414573

<font size = "5">

Query with string conditions

In [6]:
# When you have queries for text variables, it's important
# to use outer ' ' single quotations
# and inner double quotations.

data_treated = carfeatures.query('status == "Treatment" ')
data_control = carfeatures.query('status == "Control" ')

<font size = "5">

Treated/control should be similar

- This is the key principle of random assignment
- We can check the summary statistics

In [7]:
# The count is different because we assigned different proportions
# All other sumary statistics are approximately the same
# They are not identical because the assignment is random

display(data_treated.describe())
display(data_control.describe())

              mpg   cylinders  displacement       weight  acceleration
count  165.000000  165.000000    165.000000   165.000000    165.000000
mean    23.167879    5.569697    198.666667  3002.757576     15.487273
std      7.818201    1.718707    104.572960   853.949920      2.624467
min     11.000000    3.000000     70.000000  1755.000000      9.500000
25%     17.000000    4.000000     98.000000  2202.000000     13.700000
50%     21.500000    6.000000    151.000000  2905.000000     15.400000
75%     28.800000    8.000000    302.000000  3672.000000     17.000000
max     46.600000    8.000000    455.000000  4997.000000     24.800000

              mpg   cylinders  displacement       weight  acceleration
count  233.000000  233.000000    233.000000   233.000000    233.000000
mean    23.760086    5.373391    189.716738  2947.527897     15.625322
std      7.821918    1.687320    104.117956   842.861838      2.852465
min      9.000000    3.000000     68.000000  1613.000000      8.000000
25%     17.500000    4.000000    105.000000  2246.000000     14.000000
50%     23.900000    4.000000    140.000000  2720.000000     15.500000
75%     29.000000    6.000000    258.000000  3520.000000     17.300000
max     44.600000    8.000000    455.000000  5140.000000     24.600000

## <span style="color:darkblue"> III. Quiz Structure </span>

<font size = "5">

The day of the quiz I will ...
- Provide a dataset with information
- Give more specific instructions.
- Below, you will see the type of questions that will be asked.
- The idea is for you to apply known concepts to new data
- You have 50 minutes to complete the assignment

Questions

(exact wording may change in quiz, but exercise will be very similar)

<font size = "5">

(a) Create a function and apply it to a column

- Check Lecture 8 for how to define a function
- The function will have if/else statements and output a string
- You will use ".apply()" to create a new variable in the dataset <br>
(see Lecture 9)

In [11]:
acceleration = carfeatures["acceleration"]
new_acceleration = []
def sorting_function():
    for i in carfeatures:
        if acceleration >= 100:
            category = "fast"
        elif acceleration <100 & acceleration>= 50:
            category = "moderate"
        elif acceleration <50:
            category = "slow"
        return category
        # new_acceleration.append(category)
carfeatures['speed_type'] = carfeatures["acceleration"].apply(sorting_function())

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [ ]:

#make dataframe
data  = pd.DataFrame([])

#lambda function
fn_iseligible_vote = lambda age: age >= 18
fn_istwenties      = lambda age: (age >= 20) & (age < 30)
fn_sum             = lambda x,y: x + y

#.apply()
data["can_vote"]    = data["age"].apply(fn_iseligible_vote)
data["in_twenties"] = data["age"].apply(fn_istwenties)
data["age_bracket"] = data["age"].apply(fn_agebracket)

#list(map()) with multiple arguments
data["num_siblings"] = list(map(fn_sum,data["num_underage_siblings"],data["num_adult_siblings"]))

#IF/ELSE function
def fn_agebracket(age):
    if (age >= 18):
        status = "Adult"
    elif (age >= 10) & (age < 18):
        status = "Adolescent"
    else:
        status = "Child"
    return(status)

#Subsets
list_subsetcols     = ["weight","mpg"]
subcols_carfeatures = carfeatures[list_subsetcols]
display(subcols_carfeatures)

#Extract column names
car_colnames = carfeatures.columns.values
print(car_colnames)

#Sort by column
carsorted = carfeatures.sort_values(by = "mpg", ascending = False)

#Subset with iloc
display(carsorted.iloc[[0,1,2],:])

#Query
data_threshold_mpg  = carfeatures.query("mpg >= 25")
data_rangeweight    = carfeatures.query("(acceleration >= 10) & (acceleration < 18)")

#unique
list_unique_cylinders = pd.unique(carfeatures["cylinders"])
print(list_unique_cylinders)

#Scatter plot

df_8 = carfeatures.query("cylinders == 8")
df_4 = carfeatures.query("cylinders == 4")

plt.scatter(x = df_8["weight"],y = df_8["acceleration"])
plt.scatter(x = df_4["weight"],y = df_4["acceleration"])
plt.legend(labels = ["8","4"],
           title  = "Cylinders")

plt.show()

#with multiple categories
list_unique_cylinders = pd.unique(carfeatures["cylinders"])

for category in list_unique_cylinders:
    df   = carfeatures.query("cylinders == @category")
    plt.scatter(x = df["weight"],y = df["acceleration"])
    
plt.xlabel("Weight")
plt.ylabel("Acceleration")
plt.legend(labels = list_unique_cylinders,
           title  = "Cylinders")
plt.show()

#mean
dataset["error_sqr"].mean

<font size = "5">

(b) Use queries + global variables

- You will be asked to compute certain summary statistics <br>
(mean, median, etc)
- The query will have multiple conditions
- Then subset a dataset that meets certain conditions
- See Lecture 10 for more details

In [16]:
mean = carfeatures["acceleration"].mean()
median = carfeatures["acceleration"].median()
mode = carfeatures["acceleration"].mode()
display(mean)
display(median)
display(mode)

data_threshold_acceleration  = carfeatures.query("acceleration >= 15")

data_threshold_acceleration

15.568090452261307

15.5

0    14.5
Name: acceleration, dtype: float64

,mpg,cylinders,displacement,horsepower,weight,acceleration,vehicle_id,status
14,24.0,4,113,95,2372,15.0,T-1689934,Treatment
15,22.0,6,198,95,2833,15.5,P-1689945,Treatment
16,18.0,6,199,97,2774,15.5,A-1689956,Treatment
17,21.0,6,200,85,2587,16.0,F-1689967,Control
19,26.0,4,97,46,1835,20.5,V-1689989,Control
...,...,...,...,...,...,...,...,...
392,27.0,4,151,90,2950,17.3,C-1694092,Control
393,27.0,4,140,86,2790,15.6,F-1694103,Treatment
394,44.0,4,97,52,2130,24.6,V-1694114,Control
396,28.0,4,120,79,2625,18.6,F-1694136,Control
397,31.0,4,119,82,2720,19.4,C-1694147,Control

<font size = "5">

(c) Use sorting + ".iloc[]"

- Extract the observations with the largest values of a column
- See Lecture 10 for details

In [17]:
carsorted = carfeatures.sort_values(by = "mpg", ascending = False)
carsorted.iloc[[0,1,2],:]

,mpg,cylinders,displacement,horsepower,weight,acceleration,vehicle_id,status
322,46.6,4,86,65,2110,17.9,M-1693322,Treatment
329,44.6,4,91,67,1850,13.8,H-1693399,Control
325,44.3,4,90,48,2085,21.7,V-1693355,Control

<font size = "5">

(d) Split a dataset into subsets

- You will be asked to randomly assign a status to each row
- Split the data into separate datasets using ".query()"
- This will closely follow the material in Lecture 12 (this one)
- You will need this result to answer questions (e), (f)

In [20]:
carfeatures["status"] = np.random.choice(list_status,
                                         size = size_dataset,
                                         p = prop_status)
carfeatures_treatment = carfeatures.query("status == 'Treatment'")
carfeatures_control = carfeatures.query("status == 'Control'")

<font size = "5">

(e) Create a function with four inputs $f(y,x,b0,b1)$

- Start by using "def" to define the function
- The function will include arithmetic operations (Lecture 3) <br>
and summary statistics for pandas (mean, std, min, max, etc.)
- You will be asked to test different values of $(y,x,b0,b1)$
- You will get $y$ and $x$ from the two datasets in part (d)
- Note: You will **not** be required to use the "statsmodels" library

In [22]:
control_accel = carfeatures_control.acceleration.mean()
treatment_accel = carfeatures_treatment.acceleration.mean()

def fn_calc(y, x, b0, b1):
    return y = b1*x + b0


# list_unique_cylinders = pd.unique(carfeatures["cylinders"])

# for category in list_unique_cylinders:
#     df   = carfeatures.query("cylinders == @category")
#     plt.scatter(x = df["weight"],y = df["acceleration"])
    
# plt.xlabel("Weight")
# plt.ylabel("Acceleration")
# plt.legend(labels = list_unique_cylinders,
#            title  = "Cylinders")
# plt.show()

15.873099415204678

<font size = "5">

(f) Create two overlapping histogram plots

- You will use a variable from the two datasets in (d)
- You need to use the "alpha" option to make the graphs semitransparent
- You will need to add a legend, label the axes, and the title
- Note: The goal of this question is to illustrate that random <br>
assignment produces very similar distributions between two groups

In [31]:
# list_unique_status = pd.unique(carfeatures["status"])

# Use a for loop to plot a scatter plot between "weight" and "acceleration"
# for each category. Each plot  will have a different color

# for category in list_unique_status:
    # df   = carfeatures.query("status == @category")
    # plt.scatter(x = df["acceleration"], alpha = 0.5)
    
# Add labels and a legends    
# plt.xlabel("acceleration")
# plt.legend(labels = list_unique_status,
#            title  = "Status")
# plt.show()
def fn_predict(b0, b1):
    for i in carfeatures.weight:
        b0 + b1*i
    return carfeatures["prediction"]

fn_predict (1, 2)

plt.scatter(x = carfeatures_control["weight"],y = carfeatures_control["acceleration"])
plt.scatter(x = carfeatures_treatment["weight"],y = carfeatures_treatment["acceleration"])
plt.scatter(x=carfeatures["weight"], y =carfeatures["prediction"])
plt.legend(labels = ["control","treatment"],
           title  = "status")

KeyError: 'prediction'